### ISSUE TITLE
Make a new release for Swift Package Manager support

### ISSUE THREAD

**Issue by loiclec** [postmates/PMJSON#11]
0399644 fixed a bug that broke SwiftPM support. However, the current release (`2.0.0`)  doesn't include this fix, therefore it is not possible to add PMJSON as a dependency of a SwiftPM project.

Could you add a tag (e.g. 2.1.0 ) to the repo please? :)
Thank you!

**Comment by kballard** [comment]
Done. Tagged as [v2.0.1](https://github.com/postmates/PMJSON/releases/tag/v2.0.1).
