### ISSUE TITLE
Consider supporting parsing Date from seconds to epoch value

### ISSUE THREAD

**Issue by nekonari** [postmates/PMJSON#24]
So we can parse `1534379998` to `Thursday, Aug 16, 2018 12:39:58AM GMT`.

**Comment by kballard** [comment]
Isn't this already provided by `JSON.Decoder.DateDecodingStrategy.secondsSince1970` and `JSON.Encoder.DateEncodingStrategy.secondsSince1970`?

**Comment by nekonari** [comment]
I wasn’t aware of strategies. How do I use them? Or I’ll look at doc later today.

**Comment by kballard** [comment]
Exactly the same way it works with the standard library's `JSONDecoder` and `JSONEncoder`; namely, the decoder and encoder have properties you can assign to such as `JSONDecoder.dateDecodingStrategy` to control the strategy for that particular decoder/encoder instances (they have properties for date, data, and the key decoding strategy).

**Comment by nekonari** [comment]
I ended up using `PMKUtilities.JSONDecodable` protocol extension and added a convenience method (`getDateSecondsSince1970(_:)`) for taking care of this.

I tried to use the decoder, but it wasn't what I needed. I just wanted a simple call `json.getDate(...)`. Using this strategy meant creating decoder, get the JSON value, unwrap it, call this method for just one value when all other values I could deserialize with a simple call like above.

**Comment by kballard** [comment]
Oh I see what you were asking for now.

I'm going to go ahead and close out this ticket. The core `JSON` behaviors are all about manipulating JSON data, and you're supposed to wrap them if you want to convert non-JSON types (such as `Date`) to/from JSON. `JSON.Decoder` and `JSON.Encoder` are the built-in mechanisms for converting non-JSON types to/from JSON, and those mechanisms already support what you're asking for with `Date`s. So if you want to have a convenient way to convert a `Date` to/from JSON, and you're not using `JSON.Decoder` or `JSON.Encoder`, then you should just extend `JSON` yourself to handle this.
